// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQDojs4kv0UkTnTUJxGp4v_DMO_Npm-tg',
    appId: '1:809419796380:web:bc497a842640e284da6259',
    messagingSenderId: '809419796380',
    projectId: 'tutur-id',
    authDomain: 'tutur-id.firebaseapp.com',
    storageBucket: 'tutur-id.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx3UwSUc7-NVddh7RPCqxSQMV9bO9x9v0',
    appId: '1:809419796380:android:2536eace40e71490da6259',
    messagingSenderId: '809419796380',
    projectId: 'tutur-id',
    storageBucket: 'tutur-id.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI6381jRgOkXvHw_s6ujkD9eDzvSvVioQ',
    appId: '1:809419796380:ios:97eba793ea09f6d1da6259',
    messagingSenderId: '809419796380',
    projectId: 'tutur-id',
    storageBucket: 'tutur-id.firebasestorage.app',
    androidClientId: '809419796380-938kesjjnu96aooo105n3igne1rgm14d.apps.googleusercontent.com',
    iosClientId: '809419796380-2q3p62cu9psdsdhb269jemhlbh5osf26.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuturIdApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI6381jRgOkXvHw_s6ujkD9eDzvSvVioQ',
    appId: '1:809419796380:ios:97eba793ea09f6d1da6259',
    messagingSenderId: '809419796380',
    projectId: 'tutur-id',
    storageBucket: 'tutur-id.firebasestorage.app',
    androidClientId: '809419796380-938kesjjnu96aooo105n3igne1rgm14d.apps.googleusercontent.com',
    iosClientId: '809419796380-2q3p62cu9psdsdhb269jemhlbh5osf26.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuturIdApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQDojs4kv0UkTnTUJxGp4v_DMO_Npm-tg',
    appId: '1:809419796380:web:da340d3baf99f056da6259',
    messagingSenderId: '809419796380',
    projectId: 'tutur-id',
    authDomain: 'tutur-id.firebaseapp.com',
    storageBucket: 'tutur-id.firebasestorage.app',
  );
}
